# =============================================
# springboot configurations
# ---------------------------------------------
spring:
  application:
    name: fuse-medical-integration-api
  datasource:
    initialize: false

api:
  version: 1

logging:
  config: classpath:logback.xml

# options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
camel:
  springboot:
    name: fuse-medical-integration-api
    main-run-controller: true
  component:
    servlet:
      mapping:
        contextPath: /api/v${api.version}/*
    jmxEnabled: true

# lets listen on all ports to ensure we can be invoked from the pod ip address
server:
  address: 0.0.0.0
  port: 8080

# lets use a different management port in case you need to listen to HTTP requests on 8080
management:
  security:
    enabled: false
  address: 0.0.0.0
  port: 8081

# =============================================
# springboot actuator configurations
# ---------------------------------------------
# disable all management endpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true

# =============================================
# nutritionist api parameters
# ---------------------------------------------
# http://localhost:8070/api/v1/event
nutritionist:
  host: 127.0.0.1
  port: 8070
  contextPath: /api/v1/event
  apiKeyName: Nutritionist-API-User-Key

# =============================================
# cardiologist api parameters
# ---------------------------------------------
# http://localhost:8070/api/v1/event
cardiologist:
  host: 127.0.0.1
  port: 8070
  contextPath: /api/v1/event
  apiKeyName: Cardiologist-API-User-Key
