integration:
  medical:
    nutritionist:
      host: medical-integration-api-metrics.microservices.svc.cluster.local
      port: 8080
      path: /api/v1/medical/nutritionist
      apiKey: Nutritionist-API-User-Key
    cardiologist:
      host: medical-integration-api-metrics.microservices.svc.cluster.local
      port: 8080
      path: /api/v1/medical/cardiologist
      apiKey: Cardiologist-API-User-Key
