api:
  version: 1

logging:
  config: classpath:logback.xml

# lets listen on all ports to ensure we can be invoked from the pod ip address
# contextPath: /api/v${api.version}/*
server:
  address: 0.0.0.0
  port: 8090

# =============================================
# spring configurations
# ---------------------------------------------
spring:
  application:
    name: polar-flow-api
  jpa:
    # log generated sql
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: create-drop
  h2:
    # http://localhost:8080/h2-console
    # connection url: jdbc:h2:mem:testdb
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jackson:
    # JACKSON (JacksonProperties)
    # Date format string or a fully-qualified date format class name
    #spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps: true

# =============================================
# google api parameters
# ---------------------------------------------
# http://localhost:8070/api/v1/event
integration:
  social:
    strava:
      host: 127.0.0.1
      port: 8080
      path: /api/v1/social/strava
      apiKey: Strava-API-User-Key
    myfitnesspal:
      host: 127.0.0.1
      port: 8080
      path: /api/v1/social/myfitnesspal
      apiKey: MyFitnessPal-API-User-Key
    applehealth:
      host: 127.0.0.1
      port: 8080
      path: /api/v1/social/applehealth
      apiKey: AppleHealth-API-User-Key
  medical:
    nutritionist:
      host: 127.0.0.1
      port: 8080
      path: /api/v1/medical/nutritionist
      apiKey: Nutritionist-API-User-Key
    cardiologist:
      host: 127.0.0.1
      port: 8080
      path: /api/v1/medical/cardiologist
      apiKey: Cardiologist-API-User-Key
  calendar:
    google:
      host: 127.0.0.1
      port: 8080
      path: /api/v1/calendar
      apiKey: Google-Calendar-API-User-Key
